# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import coldpath_pb2 as coldpath__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coldpath_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ColdPathJobsStub:
    """HotPath -> ColdPath (async job submission)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTrainingData = channel.unary_unary(
                '/sniperdesk.coldpath.ColdPathJobs/SubmitTrainingData',
                request_serializer=coldpath__pb2.TrainingDataBatch.SerializeToString,
                response_deserializer=coldpath__pb2.JobAck.FromString,
                _registered_method=True)
        self.RequestCalibration = channel.unary_unary(
                '/sniperdesk.coldpath.ColdPathJobs/RequestCalibration',
                request_serializer=coldpath__pb2.CalibrationRequest.SerializeToString,
                response_deserializer=coldpath__pb2.CalibrationResult.FromString,
                _registered_method=True)
        self.GetModelParams = channel.unary_unary(
                '/sniperdesk.coldpath.ColdPathJobs/GetModelParams',
                request_serializer=coldpath__pb2.ParamRequest.SerializeToString,
                response_deserializer=coldpath__pb2.ModelParams.FromString,
                _registered_method=True)
        self.GetBacktestData = channel.unary_stream(
                '/sniperdesk.coldpath.ColdPathJobs/GetBacktestData',
                request_serializer=coldpath__pb2.BacktestDataRequest.SerializeToString,
                response_deserializer=coldpath__pb2.BacktestEvent.FromString,
                _registered_method=True)


class ColdPathJobsServicer:
    """HotPath -> ColdPath (async job submission)
    """

    def SubmitTrainingData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCalibration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBacktestData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ColdPathJobsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTrainingData': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTrainingData,
                    request_deserializer=coldpath__pb2.TrainingDataBatch.FromString,
                    response_serializer=coldpath__pb2.JobAck.SerializeToString,
            ),
            'RequestCalibration': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCalibration,
                    request_deserializer=coldpath__pb2.CalibrationRequest.FromString,
                    response_serializer=coldpath__pb2.CalibrationResult.SerializeToString,
            ),
            'GetModelParams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelParams,
                    request_deserializer=coldpath__pb2.ParamRequest.FromString,
                    response_serializer=coldpath__pb2.ModelParams.SerializeToString,
            ),
            'GetBacktestData': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBacktestData,
                    request_deserializer=coldpath__pb2.BacktestDataRequest.FromString,
                    response_serializer=coldpath__pb2.BacktestEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.coldpath.ColdPathJobs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.coldpath.ColdPathJobs', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ColdPathJobs:
    """HotPath -> ColdPath (async job submission)
    """

    @staticmethod
    def SubmitTrainingData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.ColdPathJobs/SubmitTrainingData',
            coldpath__pb2.TrainingDataBatch.SerializeToString,
            coldpath__pb2.JobAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestCalibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.ColdPathJobs/RequestCalibration',
            coldpath__pb2.CalibrationRequest.SerializeToString,
            coldpath__pb2.CalibrationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.ColdPathJobs/GetModelParams',
            coldpath__pb2.ParamRequest.SerializeToString,
            coldpath__pb2.ModelParams.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBacktestData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sniperdesk.coldpath.ColdPathJobs/GetBacktestData',
            coldpath__pb2.BacktestDataRequest.SerializeToString,
            coldpath__pb2.BacktestEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ParamPublisherStub:
    """ColdPath -> HotPath (parameter push)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushParams = channel.unary_unary(
                '/sniperdesk.coldpath.ParamPublisher/PushParams',
                request_serializer=coldpath__pb2.ModelParams.SerializeToString,
                response_deserializer=coldpath__pb2.PushAck.FromString,
                _registered_method=True)


class ParamPublisherServicer:
    """ColdPath -> HotPath (parameter push)
    """

    def PushParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParamPublisherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushParams': grpc.unary_unary_rpc_method_handler(
                    servicer.PushParams,
                    request_deserializer=coldpath__pb2.ModelParams.FromString,
                    response_serializer=coldpath__pb2.PushAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.coldpath.ParamPublisher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.coldpath.ParamPublisher', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParamPublisher:
    """ColdPath -> HotPath (parameter push)
    """

    @staticmethod
    def PushParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.ParamPublisher/PushParams',
            coldpath__pb2.ModelParams.SerializeToString,
            coldpath__pb2.PushAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModelArtifactServiceStub:
    """ColdPath -> HotPath (model artifact push for ML runtime)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushArtifact = channel.unary_unary(
                '/sniperdesk.coldpath.ModelArtifactService/PushArtifact',
                request_serializer=coldpath__pb2.ModelArtifact.SerializeToString,
                response_deserializer=coldpath__pb2.ArtifactPushResponse.FromString,
                _registered_method=True)
        self.GetArtifactStatus = channel.unary_unary(
                '/sniperdesk.coldpath.ModelArtifactService/GetArtifactStatus',
                request_serializer=coldpath__pb2.ArtifactStatusRequest.SerializeToString,
                response_deserializer=coldpath__pb2.ArtifactStatusResponse.FromString,
                _registered_method=True)
        self.RollbackArtifact = channel.unary_unary(
                '/sniperdesk.coldpath.ModelArtifactService/RollbackArtifact',
                request_serializer=coldpath__pb2.RollbackRequest.SerializeToString,
                response_deserializer=coldpath__pb2.RollbackResponse.FromString,
                _registered_method=True)


class ModelArtifactServiceServicer:
    """ColdPath -> HotPath (model artifact push for ML runtime)
    """

    def PushArtifact(self, request, context):
        """Push a trained model artifact for hot-reload
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifactStatus(self, request, context):
        """Get current artifact status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackArtifact(self, request, context):
        """Trigger rollback to previous version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelArtifactServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.PushArtifact,
                    request_deserializer=coldpath__pb2.ModelArtifact.FromString,
                    response_serializer=coldpath__pb2.ArtifactPushResponse.SerializeToString,
            ),
            'GetArtifactStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifactStatus,
                    request_deserializer=coldpath__pb2.ArtifactStatusRequest.FromString,
                    response_serializer=coldpath__pb2.ArtifactStatusResponse.SerializeToString,
            ),
            'RollbackArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackArtifact,
                    request_deserializer=coldpath__pb2.RollbackRequest.FromString,
                    response_serializer=coldpath__pb2.RollbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.coldpath.ModelArtifactService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.coldpath.ModelArtifactService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelArtifactService:
    """ColdPath -> HotPath (model artifact push for ML runtime)
    """

    @staticmethod
    def PushArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.ModelArtifactService/PushArtifact',
            coldpath__pb2.ModelArtifact.SerializeToString,
            coldpath__pb2.ArtifactPushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifactStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.ModelArtifactService/GetArtifactStatus',
            coldpath__pb2.ArtifactStatusRequest.SerializeToString,
            coldpath__pb2.ArtifactStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.ModelArtifactService/RollbackArtifact',
            coldpath__pb2.RollbackRequest.SerializeToString,
            coldpath__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AnnouncementProcessorStub:
    """Announcement Processing Service (HotPath -> ColdPath)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessBatch = channel.unary_unary(
                '/sniperdesk.coldpath.AnnouncementProcessor/ProcessBatch',
                request_serializer=coldpath__pb2.AnnouncementBatch.SerializeToString,
                response_deserializer=coldpath__pb2.ProcessedBatch.FromString,
                _registered_method=True)
        self.ClassifyBatch = channel.unary_unary(
                '/sniperdesk.coldpath.AnnouncementProcessor/ClassifyBatch',
                request_serializer=coldpath__pb2.AnnouncementBatch.SerializeToString,
                response_deserializer=coldpath__pb2.ClassificationBatch.FromString,
                _registered_method=True)
        self.ExtractEntities = channel.unary_unary(
                '/sniperdesk.coldpath.AnnouncementProcessor/ExtractEntities',
                request_serializer=coldpath__pb2.Announcement.SerializeToString,
                response_deserializer=coldpath__pb2.ExtractedEntities.FromString,
                _registered_method=True)
        self.VerifyOnChain = channel.unary_unary(
                '/sniperdesk.coldpath.AnnouncementProcessor/VerifyOnChain',
                request_serializer=coldpath__pb2.VerificationRequest.SerializeToString,
                response_deserializer=coldpath__pb2.VerificationResult.FromString,
                _registered_method=True)
        self.GetSourceReputation = channel.unary_unary(
                '/sniperdesk.coldpath.AnnouncementProcessor/GetSourceReputation',
                request_serializer=coldpath__pb2.SourceReputationRequest.SerializeToString,
                response_deserializer=coldpath__pb2.SourceReputationResponse.FromString,
                _registered_method=True)
        self.RecordOutcome = channel.unary_unary(
                '/sniperdesk.coldpath.AnnouncementProcessor/RecordOutcome',
                request_serializer=coldpath__pb2.OutcomeRecord.SerializeToString,
                response_deserializer=coldpath__pb2.JobAck.FromString,
                _registered_method=True)


class AnnouncementProcessorServicer:
    """Announcement Processing Service (HotPath -> ColdPath)
    """

    def ProcessBatch(self, request, context):
        """Process a batch of announcements through full pipeline
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyBatch(self, request, context):
        """Classify announcements only (fast path)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractEntities(self, request, context):
        """Extract entities from a single announcement (uses Opus for complex cases)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOnChain(self, request, context):
        """Verify token on-chain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSourceReputation(self, request, context):
        """Get source reputation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordOutcome(self, request, context):
        """Record outcome for learning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnnouncementProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessBatch,
                    request_deserializer=coldpath__pb2.AnnouncementBatch.FromString,
                    response_serializer=coldpath__pb2.ProcessedBatch.SerializeToString,
            ),
            'ClassifyBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyBatch,
                    request_deserializer=coldpath__pb2.AnnouncementBatch.FromString,
                    response_serializer=coldpath__pb2.ClassificationBatch.SerializeToString,
            ),
            'ExtractEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractEntities,
                    request_deserializer=coldpath__pb2.Announcement.FromString,
                    response_serializer=coldpath__pb2.ExtractedEntities.SerializeToString,
            ),
            'VerifyOnChain': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOnChain,
                    request_deserializer=coldpath__pb2.VerificationRequest.FromString,
                    response_serializer=coldpath__pb2.VerificationResult.SerializeToString,
            ),
            'GetSourceReputation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSourceReputation,
                    request_deserializer=coldpath__pb2.SourceReputationRequest.FromString,
                    response_serializer=coldpath__pb2.SourceReputationResponse.SerializeToString,
            ),
            'RecordOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordOutcome,
                    request_deserializer=coldpath__pb2.OutcomeRecord.FromString,
                    response_serializer=coldpath__pb2.JobAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.coldpath.AnnouncementProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.coldpath.AnnouncementProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnnouncementProcessor:
    """Announcement Processing Service (HotPath -> ColdPath)
    """

    @staticmethod
    def ProcessBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.AnnouncementProcessor/ProcessBatch',
            coldpath__pb2.AnnouncementBatch.SerializeToString,
            coldpath__pb2.ProcessedBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.AnnouncementProcessor/ClassifyBatch',
            coldpath__pb2.AnnouncementBatch.SerializeToString,
            coldpath__pb2.ClassificationBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.AnnouncementProcessor/ExtractEntities',
            coldpath__pb2.Announcement.SerializeToString,
            coldpath__pb2.ExtractedEntities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOnChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.AnnouncementProcessor/VerifyOnChain',
            coldpath__pb2.VerificationRequest.SerializeToString,
            coldpath__pb2.VerificationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSourceReputation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.AnnouncementProcessor/GetSourceReputation',
            coldpath__pb2.SourceReputationRequest.SerializeToString,
            coldpath__pb2.SourceReputationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.coldpath.AnnouncementProcessor/RecordOutcome',
            coldpath__pb2.OutcomeRecord.SerializeToString,
            coldpath__pb2.JobAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
