# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import hotpath_pb2 as hotpath__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hotpath_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HotPathControlStub:
    """SwiftUI -> HotPath
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetExecutionMode = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/SetExecutionMode',
                request_serializer=hotpath__pb2.SetModeRequest.SerializeToString,
                response_deserializer=hotpath__pb2.SetModeResponse.FromString,
                _registered_method=True)
        self.UpdateRiskLimits = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/UpdateRiskLimits',
                request_serializer=hotpath__pb2.RiskLimitsRequest.SerializeToString,
                response_deserializer=hotpath__pb2.RiskLimitsResponse.FromString,
                _registered_method=True)
        self.SubmitSignedTx = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/SubmitSignedTx',
                request_serializer=hotpath__pb2.SignedTxRequest.SerializeToString,
                response_deserializer=hotpath__pb2.SignedTxResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/GetStatus',
                request_serializer=hotpath__pb2.StatusRequest.SerializeToString,
                response_deserializer=hotpath__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetApiVersion = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/GetApiVersion',
                request_serializer=hotpath__pb2.ApiVersionRequest.SerializeToString,
                response_deserializer=hotpath__pb2.ApiVersionResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/sniperdesk.hotpath.HotPathControl/StreamEvents',
                request_serializer=hotpath__pb2.StreamRequest.SerializeToString,
                response_deserializer=hotpath__pb2.Event.FromString,
                _registered_method=True)
        self.KillSwitch = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/KillSwitch',
                request_serializer=hotpath__pb2.KillRequest.SerializeToString,
                response_deserializer=hotpath__pb2.KillResponse.FromString,
                _registered_method=True)
        self.GetTokenData = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/GetTokenData',
                request_serializer=hotpath__pb2.TokenDataRequest.SerializeToString,
                response_deserializer=hotpath__pb2.TokenDataResponse.FromString,
                _registered_method=True)
        self.RefreshTokenData = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/RefreshTokenData',
                request_serializer=hotpath__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=hotpath__pb2.TokenDataResponse.FromString,
                _registered_method=True)
        self.TrackToken = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/TrackToken',
                request_serializer=hotpath__pb2.TrackTokenRequest.SerializeToString,
                response_deserializer=hotpath__pb2.TrackTokenResponse.FromString,
                _registered_method=True)
        self.UntrackToken = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/UntrackToken',
                request_serializer=hotpath__pb2.TrackTokenRequest.SerializeToString,
                response_deserializer=hotpath__pb2.TrackTokenResponse.FromString,
                _registered_method=True)
        self.GetCacheStats = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/GetCacheStats',
                request_serializer=hotpath__pb2.CacheStatsRequest.SerializeToString,
                response_deserializer=hotpath__pb2.CacheStatsResponse.FromString,
                _registered_method=True)
        self.InvalidateCache = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/InvalidateCache',
                request_serializer=hotpath__pb2.InvalidateCacheRequest.SerializeToString,
                response_deserializer=hotpath__pb2.InvalidateCacheResponse.FromString,
                _registered_method=True)
        self.SubmitTradingSignal = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/SubmitTradingSignal',
                request_serializer=hotpath__pb2.TradingSignalRequest.SerializeToString,
                response_deserializer=hotpath__pb2.TradingSignalResponse.FromString,
                _registered_method=True)
        self.SubmitTradingSignalBatch = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/SubmitTradingSignalBatch',
                request_serializer=hotpath__pb2.TradingSignalBatch.SerializeToString,
                response_deserializer=hotpath__pb2.TradingSignalBatchResponse.FromString,
                _registered_method=True)
        self.ReportTradeOutcome = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/ReportTradeOutcome',
                request_serializer=hotpath__pb2.TradeOutcomeRequest.SerializeToString,
                response_deserializer=hotpath__pb2.TradeOutcomeResponse.FromString,
                _registered_method=True)
        self.ConfigureChain = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/ConfigureChain',
                request_serializer=hotpath__pb2.ChainConfigRequest.SerializeToString,
                response_deserializer=hotpath__pb2.ChainConfigResponse.FromString,
                _registered_method=True)
        self.GetChainStatus = channel.unary_unary(
                '/sniperdesk.hotpath.HotPathControl/GetChainStatus',
                request_serializer=hotpath__pb2.ChainStatusRequest.SerializeToString,
                response_deserializer=hotpath__pb2.ChainStatusResponse.FromString,
                _registered_method=True)
        self.StreamMultiChainEvents = channel.unary_stream(
                '/sniperdesk.hotpath.HotPathControl/StreamMultiChainEvents',
                request_serializer=hotpath__pb2.MultiChainStreamRequest.SerializeToString,
                response_deserializer=hotpath__pb2.MultiChainCandidate.FromString,
                _registered_method=True)


class HotPathControlServicer:
    """SwiftUI -> HotPath
    """

    def SetExecutionMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRiskLimits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSignedTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApiVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KillSwitch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTokenData(self, request, context):
        """Cache management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshTokenData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UntrackToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCacheStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTradingSignal(self, request, context):
        """AutoTrader integration (ColdPath -> HotPath)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTradingSignalBatch(self, request, context):
        """Batch submission for 100x reduced RPC overhead (submit multiple signals in single call)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTradeOutcome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureChain(self, request, context):
        """Multi-chain support
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChainStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMultiChainEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HotPathControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetExecutionMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetExecutionMode,
                    request_deserializer=hotpath__pb2.SetModeRequest.FromString,
                    response_serializer=hotpath__pb2.SetModeResponse.SerializeToString,
            ),
            'UpdateRiskLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRiskLimits,
                    request_deserializer=hotpath__pb2.RiskLimitsRequest.FromString,
                    response_serializer=hotpath__pb2.RiskLimitsResponse.SerializeToString,
            ),
            'SubmitSignedTx': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSignedTx,
                    request_deserializer=hotpath__pb2.SignedTxRequest.FromString,
                    response_serializer=hotpath__pb2.SignedTxResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=hotpath__pb2.StatusRequest.FromString,
                    response_serializer=hotpath__pb2.StatusResponse.SerializeToString,
            ),
            'GetApiVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApiVersion,
                    request_deserializer=hotpath__pb2.ApiVersionRequest.FromString,
                    response_serializer=hotpath__pb2.ApiVersionResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=hotpath__pb2.StreamRequest.FromString,
                    response_serializer=hotpath__pb2.Event.SerializeToString,
            ),
            'KillSwitch': grpc.unary_unary_rpc_method_handler(
                    servicer.KillSwitch,
                    request_deserializer=hotpath__pb2.KillRequest.FromString,
                    response_serializer=hotpath__pb2.KillResponse.SerializeToString,
            ),
            'GetTokenData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenData,
                    request_deserializer=hotpath__pb2.TokenDataRequest.FromString,
                    response_serializer=hotpath__pb2.TokenDataResponse.SerializeToString,
            ),
            'RefreshTokenData': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshTokenData,
                    request_deserializer=hotpath__pb2.RefreshTokenRequest.FromString,
                    response_serializer=hotpath__pb2.TokenDataResponse.SerializeToString,
            ),
            'TrackToken': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackToken,
                    request_deserializer=hotpath__pb2.TrackTokenRequest.FromString,
                    response_serializer=hotpath__pb2.TrackTokenResponse.SerializeToString,
            ),
            'UntrackToken': grpc.unary_unary_rpc_method_handler(
                    servicer.UntrackToken,
                    request_deserializer=hotpath__pb2.TrackTokenRequest.FromString,
                    response_serializer=hotpath__pb2.TrackTokenResponse.SerializeToString,
            ),
            'GetCacheStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCacheStats,
                    request_deserializer=hotpath__pb2.CacheStatsRequest.FromString,
                    response_serializer=hotpath__pb2.CacheStatsResponse.SerializeToString,
            ),
            'InvalidateCache': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateCache,
                    request_deserializer=hotpath__pb2.InvalidateCacheRequest.FromString,
                    response_serializer=hotpath__pb2.InvalidateCacheResponse.SerializeToString,
            ),
            'SubmitTradingSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTradingSignal,
                    request_deserializer=hotpath__pb2.TradingSignalRequest.FromString,
                    response_serializer=hotpath__pb2.TradingSignalResponse.SerializeToString,
            ),
            'SubmitTradingSignalBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTradingSignalBatch,
                    request_deserializer=hotpath__pb2.TradingSignalBatch.FromString,
                    response_serializer=hotpath__pb2.TradingSignalBatchResponse.SerializeToString,
            ),
            'ReportTradeOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTradeOutcome,
                    request_deserializer=hotpath__pb2.TradeOutcomeRequest.FromString,
                    response_serializer=hotpath__pb2.TradeOutcomeResponse.SerializeToString,
            ),
            'ConfigureChain': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureChain,
                    request_deserializer=hotpath__pb2.ChainConfigRequest.FromString,
                    response_serializer=hotpath__pb2.ChainConfigResponse.SerializeToString,
            ),
            'GetChainStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChainStatus,
                    request_deserializer=hotpath__pb2.ChainStatusRequest.FromString,
                    response_serializer=hotpath__pb2.ChainStatusResponse.SerializeToString,
            ),
            'StreamMultiChainEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMultiChainEvents,
                    request_deserializer=hotpath__pb2.MultiChainStreamRequest.FromString,
                    response_serializer=hotpath__pb2.MultiChainCandidate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.hotpath.HotPathControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.hotpath.HotPathControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HotPathControl:
    """SwiftUI -> HotPath
    """

    @staticmethod
    def SetExecutionMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/SetExecutionMode',
            hotpath__pb2.SetModeRequest.SerializeToString,
            hotpath__pb2.SetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRiskLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/UpdateRiskLimits',
            hotpath__pb2.RiskLimitsRequest.SerializeToString,
            hotpath__pb2.RiskLimitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSignedTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/SubmitSignedTx',
            hotpath__pb2.SignedTxRequest.SerializeToString,
            hotpath__pb2.SignedTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/GetStatus',
            hotpath__pb2.StatusRequest.SerializeToString,
            hotpath__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApiVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/GetApiVersion',
            hotpath__pb2.ApiVersionRequest.SerializeToString,
            hotpath__pb2.ApiVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/StreamEvents',
            hotpath__pb2.StreamRequest.SerializeToString,
            hotpath__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KillSwitch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/KillSwitch',
            hotpath__pb2.KillRequest.SerializeToString,
            hotpath__pb2.KillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTokenData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/GetTokenData',
            hotpath__pb2.TokenDataRequest.SerializeToString,
            hotpath__pb2.TokenDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshTokenData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/RefreshTokenData',
            hotpath__pb2.RefreshTokenRequest.SerializeToString,
            hotpath__pb2.TokenDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/TrackToken',
            hotpath__pb2.TrackTokenRequest.SerializeToString,
            hotpath__pb2.TrackTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UntrackToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/UntrackToken',
            hotpath__pb2.TrackTokenRequest.SerializeToString,
            hotpath__pb2.TrackTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCacheStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/GetCacheStats',
            hotpath__pb2.CacheStatsRequest.SerializeToString,
            hotpath__pb2.CacheStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/InvalidateCache',
            hotpath__pb2.InvalidateCacheRequest.SerializeToString,
            hotpath__pb2.InvalidateCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTradingSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/SubmitTradingSignal',
            hotpath__pb2.TradingSignalRequest.SerializeToString,
            hotpath__pb2.TradingSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTradingSignalBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/SubmitTradingSignalBatch',
            hotpath__pb2.TradingSignalBatch.SerializeToString,
            hotpath__pb2.TradingSignalBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTradeOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/ReportTradeOutcome',
            hotpath__pb2.TradeOutcomeRequest.SerializeToString,
            hotpath__pb2.TradeOutcomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/ConfigureChain',
            hotpath__pb2.ChainConfigRequest.SerializeToString,
            hotpath__pb2.ChainConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChainStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/GetChainStatus',
            hotpath__pb2.ChainStatusRequest.SerializeToString,
            hotpath__pb2.ChainStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMultiChainEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sniperdesk.hotpath.HotPathControl/StreamMultiChainEvents',
            hotpath__pb2.MultiChainStreamRequest.SerializeToString,
            hotpath__pb2.MultiChainCandidate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LLMAnalysisServiceStub:
    """============================================
    ML System Extensions
    ============================================

    LLM Analysis Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeProposal = channel.unary_unary(
                '/sniperdesk.hotpath.LLMAnalysisService/AnalyzeProposal',
                request_serializer=hotpath__pb2.LLMAnalysisRequest.SerializeToString,
                response_deserializer=hotpath__pb2.LLMAnalysisResponse.FromString,
                _registered_method=True)
        self.ExplainScore = channel.unary_unary(
                '/sniperdesk.hotpath.LLMAnalysisService/ExplainScore',
                request_serializer=hotpath__pb2.ScoreExplanationRequest.SerializeToString,
                response_deserializer=hotpath__pb2.ScoreExplanationResponse.FromString,
                _registered_method=True)
        self.GetRegimeAnalysis = channel.unary_unary(
                '/sniperdesk.hotpath.LLMAnalysisService/GetRegimeAnalysis',
                request_serializer=hotpath__pb2.RegimeAnalysisRequest.SerializeToString,
                response_deserializer=hotpath__pb2.RegimeAnalysisResponse.FromString,
                _registered_method=True)


class LLMAnalysisServiceServicer:
    """============================================
    ML System Extensions
    ============================================

    LLM Analysis Service
    """

    def AnalyzeProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegimeAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeProposal,
                    request_deserializer=hotpath__pb2.LLMAnalysisRequest.FromString,
                    response_serializer=hotpath__pb2.LLMAnalysisResponse.SerializeToString,
            ),
            'ExplainScore': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainScore,
                    request_deserializer=hotpath__pb2.ScoreExplanationRequest.FromString,
                    response_serializer=hotpath__pb2.ScoreExplanationResponse.SerializeToString,
            ),
            'GetRegimeAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegimeAnalysis,
                    request_deserializer=hotpath__pb2.RegimeAnalysisRequest.FromString,
                    response_serializer=hotpath__pb2.RegimeAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.hotpath.LLMAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.hotpath.LLMAnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMAnalysisService:
    """============================================
    ML System Extensions
    ============================================

    LLM Analysis Service
    """

    @staticmethod
    def AnalyzeProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.LLMAnalysisService/AnalyzeProposal',
            hotpath__pb2.LLMAnalysisRequest.SerializeToString,
            hotpath__pb2.LLMAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.LLMAnalysisService/ExplainScore',
            hotpath__pb2.ScoreExplanationRequest.SerializeToString,
            hotpath__pb2.ScoreExplanationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegimeAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.LLMAnalysisService/GetRegimeAnalysis',
            hotpath__pb2.RegimeAnalysisRequest.SerializeToString,
            hotpath__pb2.RegimeAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FeatureImportanceServiceStub:
    """Feature Importance Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMutualInformation = channel.unary_unary(
                '/sniperdesk.hotpath.FeatureImportanceService/GetMutualInformation',
                request_serializer=hotpath__pb2.MIRequest.SerializeToString,
                response_deserializer=hotpath__pb2.MIResponse.FromString,
                _registered_method=True)
        self.SelectFeatures = channel.unary_unary(
                '/sniperdesk.hotpath.FeatureImportanceService/SelectFeatures',
                request_serializer=hotpath__pb2.FeatureSelectionRequest.SerializeToString,
                response_deserializer=hotpath__pb2.FeatureSelectionResponse.FromString,
                _registered_method=True)
        self.GetFeatureRankings = channel.unary_unary(
                '/sniperdesk.hotpath.FeatureImportanceService/GetFeatureRankings',
                request_serializer=hotpath__pb2.FeatureRankingRequest.SerializeToString,
                response_deserializer=hotpath__pb2.FeatureRankingResponse.FromString,
                _registered_method=True)


class FeatureImportanceServiceServicer:
    """Feature Importance Service
    """

    def GetMutualInformation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeatureRankings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureImportanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMutualInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMutualInformation,
                    request_deserializer=hotpath__pb2.MIRequest.FromString,
                    response_serializer=hotpath__pb2.MIResponse.SerializeToString,
            ),
            'SelectFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectFeatures,
                    request_deserializer=hotpath__pb2.FeatureSelectionRequest.FromString,
                    response_serializer=hotpath__pb2.FeatureSelectionResponse.SerializeToString,
            ),
            'GetFeatureRankings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatureRankings,
                    request_deserializer=hotpath__pb2.FeatureRankingRequest.FromString,
                    response_serializer=hotpath__pb2.FeatureRankingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.hotpath.FeatureImportanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.hotpath.FeatureImportanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeatureImportanceService:
    """Feature Importance Service
    """

    @staticmethod
    def GetMutualInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.FeatureImportanceService/GetMutualInformation',
            hotpath__pb2.MIRequest.SerializeToString,
            hotpath__pb2.MIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.FeatureImportanceService/SelectFeatures',
            hotpath__pb2.FeatureSelectionRequest.SerializeToString,
            hotpath__pb2.FeatureSelectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeatureRankings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.FeatureImportanceService/GetFeatureRankings',
            hotpath__pb2.FeatureRankingRequest.SerializeToString,
            hotpath__pb2.FeatureRankingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SlotSimulationServiceStub:
    """Slot Simulation Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimulateTransaction = channel.unary_unary(
                '/sniperdesk.hotpath.SlotSimulationService/SimulateTransaction',
                request_serializer=hotpath__pb2.SlotSimRequest.SerializeToString,
                response_deserializer=hotpath__pb2.SlotSimResponse.FromString,
                _registered_method=True)
        self.EstimateOptimalFee = channel.unary_unary(
                '/sniperdesk.hotpath.SlotSimulationService/EstimateOptimalFee',
                request_serializer=hotpath__pb2.FeeEstimateRequest.SerializeToString,
                response_deserializer=hotpath__pb2.FeeEstimateResponse.FromString,
                _registered_method=True)


class SlotSimulationServiceServicer:
    """Slot Simulation Service
    """

    def SimulateTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateOptimalFee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SlotSimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimulateTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateTransaction,
                    request_deserializer=hotpath__pb2.SlotSimRequest.FromString,
                    response_serializer=hotpath__pb2.SlotSimResponse.SerializeToString,
            ),
            'EstimateOptimalFee': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateOptimalFee,
                    request_deserializer=hotpath__pb2.FeeEstimateRequest.FromString,
                    response_serializer=hotpath__pb2.FeeEstimateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.hotpath.SlotSimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.hotpath.SlotSimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SlotSimulationService:
    """Slot Simulation Service
    """

    @staticmethod
    def SimulateTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.SlotSimulationService/SimulateTransaction',
            hotpath__pb2.SlotSimRequest.SerializeToString,
            hotpath__pb2.SlotSimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateOptimalFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.SlotSimulationService/EstimateOptimalFee',
            hotpath__pb2.FeeEstimateRequest.SerializeToString,
            hotpath__pb2.FeeEstimateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PortfolioServiceStub:
    """Portfolio Optimization Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OptimizeAllocation = channel.unary_unary(
                '/sniperdesk.hotpath.PortfolioService/OptimizeAllocation',
                request_serializer=hotpath__pb2.PortfolioOptRequest.SerializeToString,
                response_deserializer=hotpath__pb2.PortfolioOptResponse.FromString,
                _registered_method=True)
        self.GetCorrelationMatrix = channel.unary_unary(
                '/sniperdesk.hotpath.PortfolioService/GetCorrelationMatrix',
                request_serializer=hotpath__pb2.CorrelationRequest.SerializeToString,
                response_deserializer=hotpath__pb2.CorrelationResponse.FromString,
                _registered_method=True)
        self.ComputeRiskParity = channel.unary_unary(
                '/sniperdesk.hotpath.PortfolioService/ComputeRiskParity',
                request_serializer=hotpath__pb2.RiskParityRequest.SerializeToString,
                response_deserializer=hotpath__pb2.RiskParityResponse.FromString,
                _registered_method=True)


class PortfolioServiceServicer:
    """Portfolio Optimization Service
    """

    def OptimizeAllocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCorrelationMatrix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeRiskParity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortfolioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OptimizeAllocation': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizeAllocation,
                    request_deserializer=hotpath__pb2.PortfolioOptRequest.FromString,
                    response_serializer=hotpath__pb2.PortfolioOptResponse.SerializeToString,
            ),
            'GetCorrelationMatrix': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCorrelationMatrix,
                    request_deserializer=hotpath__pb2.CorrelationRequest.FromString,
                    response_serializer=hotpath__pb2.CorrelationResponse.SerializeToString,
            ),
            'ComputeRiskParity': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeRiskParity,
                    request_deserializer=hotpath__pb2.RiskParityRequest.FromString,
                    response_serializer=hotpath__pb2.RiskParityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.hotpath.PortfolioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.hotpath.PortfolioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PortfolioService:
    """Portfolio Optimization Service
    """

    @staticmethod
    def OptimizeAllocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.PortfolioService/OptimizeAllocation',
            hotpath__pb2.PortfolioOptRequest.SerializeToString,
            hotpath__pb2.PortfolioOptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCorrelationMatrix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.PortfolioService/GetCorrelationMatrix',
            hotpath__pb2.CorrelationRequest.SerializeToString,
            hotpath__pb2.CorrelationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeRiskParity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.PortfolioService/ComputeRiskParity',
            hotpath__pb2.RiskParityRequest.SerializeToString,
            hotpath__pb2.RiskParityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RegimeDetectionServiceStub:
    """Regime Detection Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectRegime = channel.unary_unary(
                '/sniperdesk.hotpath.RegimeDetectionService/DetectRegime',
                request_serializer=hotpath__pb2.RegimeDetectRequest.SerializeToString,
                response_deserializer=hotpath__pb2.RegimeDetectResponse.FromString,
                _registered_method=True)
        self.GetRegimeWeights = channel.unary_unary(
                '/sniperdesk.hotpath.RegimeDetectionService/GetRegimeWeights',
                request_serializer=hotpath__pb2.RegimeWeightsRequest.SerializeToString,
                response_deserializer=hotpath__pb2.RegimeWeightsResponse.FromString,
                _registered_method=True)
        self.UpdateRegimeWeights = channel.unary_unary(
                '/sniperdesk.hotpath.RegimeDetectionService/UpdateRegimeWeights',
                request_serializer=hotpath__pb2.UpdateWeightsRequest.SerializeToString,
                response_deserializer=hotpath__pb2.UpdateWeightsResponse.FromString,
                _registered_method=True)


class RegimeDetectionServiceServicer:
    """Regime Detection Service
    """

    def DetectRegime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegimeWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRegimeWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegimeDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectRegime': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectRegime,
                    request_deserializer=hotpath__pb2.RegimeDetectRequest.FromString,
                    response_serializer=hotpath__pb2.RegimeDetectResponse.SerializeToString,
            ),
            'GetRegimeWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegimeWeights,
                    request_deserializer=hotpath__pb2.RegimeWeightsRequest.FromString,
                    response_serializer=hotpath__pb2.RegimeWeightsResponse.SerializeToString,
            ),
            'UpdateRegimeWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRegimeWeights,
                    request_deserializer=hotpath__pb2.UpdateWeightsRequest.FromString,
                    response_serializer=hotpath__pb2.UpdateWeightsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.hotpath.RegimeDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.hotpath.RegimeDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegimeDetectionService:
    """Regime Detection Service
    """

    @staticmethod
    def DetectRegime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.RegimeDetectionService/DetectRegime',
            hotpath__pb2.RegimeDetectRequest.SerializeToString,
            hotpath__pb2.RegimeDetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegimeWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.RegimeDetectionService/GetRegimeWeights',
            hotpath__pb2.RegimeWeightsRequest.SerializeToString,
            hotpath__pb2.RegimeWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRegimeWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.RegimeDetectionService/UpdateRegimeWeights',
            hotpath__pb2.UpdateWeightsRequest.SerializeToString,
            hotpath__pb2.UpdateWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MonteCarloServiceStub:
    """Monte Carlo Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunSimulation = channel.unary_unary(
                '/sniperdesk.hotpath.MonteCarloService/RunSimulation',
                request_serializer=hotpath__pb2.MonteCarloRequest.SerializeToString,
                response_deserializer=hotpath__pb2.MonteCarloResponse.FromString,
                _registered_method=True)
        self.RunSensitivityAnalysis = channel.unary_unary(
                '/sniperdesk.hotpath.MonteCarloService/RunSensitivityAnalysis',
                request_serializer=hotpath__pb2.SensitivityRequest.SerializeToString,
                response_deserializer=hotpath__pb2.SensitivityResponse.FromString,
                _registered_method=True)


class MonteCarloServiceServicer:
    """Monte Carlo Service
    """

    def RunSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSensitivityAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonteCarloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSimulation,
                    request_deserializer=hotpath__pb2.MonteCarloRequest.FromString,
                    response_serializer=hotpath__pb2.MonteCarloResponse.SerializeToString,
            ),
            'RunSensitivityAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSensitivityAnalysis,
                    request_deserializer=hotpath__pb2.SensitivityRequest.FromString,
                    response_serializer=hotpath__pb2.SensitivityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.hotpath.MonteCarloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.hotpath.MonteCarloService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MonteCarloService:
    """Monte Carlo Service
    """

    @staticmethod
    def RunSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.MonteCarloService/RunSimulation',
            hotpath__pb2.MonteCarloRequest.SerializeToString,
            hotpath__pb2.MonteCarloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSensitivityAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.MonteCarloService/RunSensitivityAnalysis',
            hotpath__pb2.SensitivityRequest.SerializeToString,
            hotpath__pb2.SensitivityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModelArtifactServiceStub:
    """Model Artifact Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListVersions = channel.unary_unary(
                '/sniperdesk.hotpath.ModelArtifactService/ListVersions',
                request_serializer=hotpath__pb2.ListVersionsRequest.SerializeToString,
                response_deserializer=hotpath__pb2.ListVersionsResponse.FromString,
                _registered_method=True)
        self.ActivateVersion = channel.unary_unary(
                '/sniperdesk.hotpath.ModelArtifactService/ActivateVersion',
                request_serializer=hotpath__pb2.ActivateVersionRequest.SerializeToString,
                response_deserializer=hotpath__pb2.ActivateVersionResponse.FromString,
                _registered_method=True)
        self.GetVersionForMint = channel.unary_unary(
                '/sniperdesk.hotpath.ModelArtifactService/GetVersionForMint',
                request_serializer=hotpath__pb2.MintRoutingRequest.SerializeToString,
                response_deserializer=hotpath__pb2.MintRoutingResponse.FromString,
                _registered_method=True)
        self.RecordTradeResult = channel.unary_unary(
                '/sniperdesk.hotpath.ModelArtifactService/RecordTradeResult',
                request_serializer=hotpath__pb2.TradeResultRequest.SerializeToString,
                response_deserializer=hotpath__pb2.TradeResultResponse.FromString,
                _registered_method=True)


class ModelArtifactServiceServicer:
    """Model Artifact Service
    """

    def ListVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersionForMint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordTradeResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelArtifactServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVersions,
                    request_deserializer=hotpath__pb2.ListVersionsRequest.FromString,
                    response_serializer=hotpath__pb2.ListVersionsResponse.SerializeToString,
            ),
            'ActivateVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateVersion,
                    request_deserializer=hotpath__pb2.ActivateVersionRequest.FromString,
                    response_serializer=hotpath__pb2.ActivateVersionResponse.SerializeToString,
            ),
            'GetVersionForMint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersionForMint,
                    request_deserializer=hotpath__pb2.MintRoutingRequest.FromString,
                    response_serializer=hotpath__pb2.MintRoutingResponse.SerializeToString,
            ),
            'RecordTradeResult': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTradeResult,
                    request_deserializer=hotpath__pb2.TradeResultRequest.FromString,
                    response_serializer=hotpath__pb2.TradeResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.hotpath.ModelArtifactService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.hotpath.ModelArtifactService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelArtifactService:
    """Model Artifact Service
    """

    @staticmethod
    def ListVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.ModelArtifactService/ListVersions',
            hotpath__pb2.ListVersionsRequest.SerializeToString,
            hotpath__pb2.ListVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.ModelArtifactService/ActivateVersion',
            hotpath__pb2.ActivateVersionRequest.SerializeToString,
            hotpath__pb2.ActivateVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersionForMint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.ModelArtifactService/GetVersionForMint',
            hotpath__pb2.MintRoutingRequest.SerializeToString,
            hotpath__pb2.MintRoutingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordTradeResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.ModelArtifactService/RecordTradeResult',
            hotpath__pb2.TradeResultRequest.SerializeToString,
            hotpath__pb2.TradeResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ABTestServiceStub:
    """A/B Testing Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateExperiment = channel.unary_unary(
                '/sniperdesk.hotpath.ABTestService/CreateExperiment',
                request_serializer=hotpath__pb2.CreateExperimentRequest.SerializeToString,
                response_deserializer=hotpath__pb2.CreateExperimentResponse.FromString,
                _registered_method=True)
        self.GetArmForMint = channel.unary_unary(
                '/sniperdesk.hotpath.ABTestService/GetArmForMint',
                request_serializer=hotpath__pb2.GetArmRequest.SerializeToString,
                response_deserializer=hotpath__pb2.GetArmResponse.FromString,
                _registered_method=True)
        self.RecordOutcome = channel.unary_unary(
                '/sniperdesk.hotpath.ABTestService/RecordOutcome',
                request_serializer=hotpath__pb2.ABOutcomeRequest.SerializeToString,
                response_deserializer=hotpath__pb2.ABOutcomeResponse.FromString,
                _registered_method=True)
        self.GetExperimentStatus = channel.unary_unary(
                '/sniperdesk.hotpath.ABTestService/GetExperimentStatus',
                request_serializer=hotpath__pb2.ExperimentStatusRequest.SerializeToString,
                response_deserializer=hotpath__pb2.ExperimentStatusResponse.FromString,
                _registered_method=True)
        self.FinalizeExperiment = channel.unary_unary(
                '/sniperdesk.hotpath.ABTestService/FinalizeExperiment',
                request_serializer=hotpath__pb2.FinalizeRequest.SerializeToString,
                response_deserializer=hotpath__pb2.FinalizeResponse.FromString,
                _registered_method=True)


class ABTestServiceServicer:
    """A/B Testing Service
    """

    def CreateExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArmForMint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordOutcome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExperimentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ABTestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateExperiment,
                    request_deserializer=hotpath__pb2.CreateExperimentRequest.FromString,
                    response_serializer=hotpath__pb2.CreateExperimentResponse.SerializeToString,
            ),
            'GetArmForMint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArmForMint,
                    request_deserializer=hotpath__pb2.GetArmRequest.FromString,
                    response_serializer=hotpath__pb2.GetArmResponse.SerializeToString,
            ),
            'RecordOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordOutcome,
                    request_deserializer=hotpath__pb2.ABOutcomeRequest.FromString,
                    response_serializer=hotpath__pb2.ABOutcomeResponse.SerializeToString,
            ),
            'GetExperimentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExperimentStatus,
                    request_deserializer=hotpath__pb2.ExperimentStatusRequest.FromString,
                    response_serializer=hotpath__pb2.ExperimentStatusResponse.SerializeToString,
            ),
            'FinalizeExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeExperiment,
                    request_deserializer=hotpath__pb2.FinalizeRequest.FromString,
                    response_serializer=hotpath__pb2.FinalizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.hotpath.ABTestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.hotpath.ABTestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ABTestService:
    """A/B Testing Service
    """

    @staticmethod
    def CreateExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.ABTestService/CreateExperiment',
            hotpath__pb2.CreateExperimentRequest.SerializeToString,
            hotpath__pb2.CreateExperimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArmForMint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.ABTestService/GetArmForMint',
            hotpath__pb2.GetArmRequest.SerializeToString,
            hotpath__pb2.GetArmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.ABTestService/RecordOutcome',
            hotpath__pb2.ABOutcomeRequest.SerializeToString,
            hotpath__pb2.ABOutcomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExperimentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.ABTestService/GetExperimentStatus',
            hotpath__pb2.ExperimentStatusRequest.SerializeToString,
            hotpath__pb2.ExperimentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.ABTestService/FinalizeExperiment',
            hotpath__pb2.FinalizeRequest.SerializeToString,
            hotpath__pb2.FinalizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FeatureServiceStub:
    """Feature Service (HotPath -> ColdPath for real-time features)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSocialFeatures = channel.unary_unary(
                '/sniperdesk.hotpath.FeatureService/GetSocialFeatures',
                request_serializer=hotpath__pb2.SocialFeaturesRequest.SerializeToString,
                response_deserializer=hotpath__pb2.SocialFeaturesResponse.FromString,
                _registered_method=True)
        self.GetOnlineFeatures = channel.unary_unary(
                '/sniperdesk.hotpath.FeatureService/GetOnlineFeatures',
                request_serializer=hotpath__pb2.OnlineFeaturesRequest.SerializeToString,
                response_deserializer=hotpath__pb2.OnlineFeaturesResponse.FromString,
                _registered_method=True)
        self.StreamSocialSignals = channel.stream_stream(
                '/sniperdesk.hotpath.FeatureService/StreamSocialSignals',
                request_serializer=hotpath__pb2.SocialSignalSubscription.SerializeToString,
                response_deserializer=hotpath__pb2.SocialSignalUpdate.FromString,
                _registered_method=True)


class FeatureServiceServicer:
    """Feature Service (HotPath -> ColdPath for real-time features)
    """

    def GetSocialFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOnlineFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSocialSignals(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSocialFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSocialFeatures,
                    request_deserializer=hotpath__pb2.SocialFeaturesRequest.FromString,
                    response_serializer=hotpath__pb2.SocialFeaturesResponse.SerializeToString,
            ),
            'GetOnlineFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOnlineFeatures,
                    request_deserializer=hotpath__pb2.OnlineFeaturesRequest.FromString,
                    response_serializer=hotpath__pb2.OnlineFeaturesResponse.SerializeToString,
            ),
            'StreamSocialSignals': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSocialSignals,
                    request_deserializer=hotpath__pb2.SocialSignalSubscription.FromString,
                    response_serializer=hotpath__pb2.SocialSignalUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sniperdesk.hotpath.FeatureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sniperdesk.hotpath.FeatureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeatureService:
    """Feature Service (HotPath -> ColdPath for real-time features)
    """

    @staticmethod
    def GetSocialFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.FeatureService/GetSocialFeatures',
            hotpath__pb2.SocialFeaturesRequest.SerializeToString,
            hotpath__pb2.SocialFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOnlineFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sniperdesk.hotpath.FeatureService/GetOnlineFeatures',
            hotpath__pb2.OnlineFeaturesRequest.SerializeToString,
            hotpath__pb2.OnlineFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSocialSignals(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sniperdesk.hotpath.FeatureService/StreamSocialSignals',
            hotpath__pb2.SocialSignalSubscription.SerializeToString,
            hotpath__pb2.SocialSignalUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
