"""Trading modules for position management and execution."""

from .adaptive_adjuster import (
    AdaptiveAdjusterConfig,
    AdaptiveParameter,
    AdaptiveParameterAdjuster,
    AdjustmentResult,
    AdjustmentTrigger,
    ParameterAdjustment,
    ParameterDirection,
    adjust_parameters_for_conditions,
    create_default_adjuster,
)
from .advanced_orchestrator import (
    AdvancedOrchestratorConfig,
    AdvancedStrategyOrchestrator,
    OrchestrationDecision,
)
from .dynamic_sl_tp import (
    ATRData,
    DynamicSLTPCalculator,
    DynamicSLTPConfig,
    DynamicSLTPResult,
    MarketCondition,
    StopLossResult,
    StopType,
    TakeProfitResult,
    calculate_dynamic_sl_tp,
)
from .kelly_criterion import (
    KellyConfig,
    KellyCriterion,
    PositionSizeResult,
    calculate_geometric_kelly,
    calculate_optimal_kelly,
)
from .profit_curve_detector import (
    AlertType,
    CurveStatistics,
    DegradationAlert,
    DegradationDetectorConfig,
    DegradationLevel,
    DegradationResult,
    DegradationType,
    ProfitCurveDegradationDetector,
    detect_profit_degradation,
)
from .volatility_sizing import (
    VolatilityCalculator,
    VolatilityConfig,
    VolatilityResult,
    VolatilityScaledSizing,
    get_volatility_sizing,
)

__all__ = [
    "KellyCriterion",
    "KellyConfig",
    "PositionSizeResult",
    "calculate_optimal_kelly",
    "calculate_geometric_kelly",
    "AdvancedOrchestratorConfig",
    "AdvancedStrategyOrchestrator",
    "OrchestrationDecision",
    "DynamicSLTPCalculator",
    "DynamicSLTPConfig",
    "DynamicSLTPResult",
    "StopLossResult",
    "TakeProfitResult",
    "ATRData",
    "MarketCondition",
    "StopType",
    "calculate_dynamic_sl_tp",
    "ProfitCurveDegradationDetector",
    "DegradationDetectorConfig",
    "DegradationResult",
    "DegradationLevel",
    "DegradationType",
    "DegradationAlert",
    "CurveStatistics",
    "AlertType",
    "detect_profit_degradation",
    "AdaptiveParameterAdjuster",
    "AdaptiveAdjusterConfig",
    "AdaptiveParameter",
    "AdjustmentResult",
    "ParameterAdjustment",
    "AdjustmentTrigger",
    "ParameterDirection",
    "create_default_adjuster",
    "adjust_parameters_for_conditions",
    # Volatility sizing
    "VolatilityScaledSizing",
    "VolatilityConfig",
    "VolatilityCalculator",
    "VolatilityResult",
    "get_volatility_sizing",
]
